// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGIPh1yVAmw6LMQQCIdWaQrhDE3pAyQ2k',
    appId: '1:1058114492252:web:d4dcf37d9b7eeb5d3a1399',
    messagingSenderId: '1058114492252',
    projectId: 'prueba-aef02',
    authDomain: 'prueba-aef02.firebaseapp.com',
    storageBucket: 'prueba-aef02.firebasestorage.app',
    measurementId: 'G-ZZZJMLBE7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1-GaVSzlQFMxocgAC_YS4ZrDvxN42jM',
    appId: '1:1058114492252:android:f750d10dd2847d1e3a1399',
    messagingSenderId: '1058114492252',
    projectId: 'prueba-aef02',
    storageBucket: 'prueba-aef02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI5j-A1qTnplZmJOBTvNH7Lgw4zc0Mgjo',
    appId: '1:1058114492252:ios:baeb1c8d07fd73463a1399',
    messagingSenderId: '1058114492252',
    projectId: 'prueba-aef02',
    storageBucket: 'prueba-aef02.firebasestorage.app',
    iosBundleId: 'com.example.libraryCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI5j-A1qTnplZmJOBTvNH7Lgw4zc0Mgjo',
    appId: '1:1058114492252:ios:baeb1c8d07fd73463a1399',
    messagingSenderId: '1058114492252',
    projectId: 'prueba-aef02',
    storageBucket: 'prueba-aef02.firebasestorage.app',
    iosBundleId: 'com.example.libraryCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGIPh1yVAmw6LMQQCIdWaQrhDE3pAyQ2k',
    appId: '1:1058114492252:web:9b9e3a9d1c0dc5c93a1399',
    messagingSenderId: '1058114492252',
    projectId: 'prueba-aef02',
    authDomain: 'prueba-aef02.firebaseapp.com',
    storageBucket: 'prueba-aef02.firebasestorage.app',
    measurementId: 'G-LN5VR54W4H',
  );
}
